
error = "red"
comment = "comment"
constant = "purple"
function = "green"
keyword = "pink"
type = { fg = "cyan", modifiers = ["italic"] }
string = "yellow"
variable = "foreground"

"ui.background" = "white"
"ui.text" = "black"

[palette]
background = "#282A36"
foreground = "#F8F8F2"
selection = "#44475A"
comment = "#6272A4"
red = "#FF5555"
orange = "#FFB86C"
yellow = "#F1FA8C"
green = "#50FA7B"
purple = "#BD93F9"
cyan = "#8BE9FD"
pink = "#FF79C6"
